When source directories aren't supplied, infer
AdRoll/rebar3_typer pull request #12
Opened 2022-01-24 21:50 UTC by maco

Priorities:
- command line arguments
- typer config in rebar.config
- src_dirs and extra_src_dirs in rebar.config
- try src and lib

Fixes #9

2022-01-25 08:35 UTC, elbrujohalcon requested changes
Does this work for umbrella apps?
I would've expected that we need to use something along the lines of [dir_for_app/1](https://github.com/AdRoll/rebar3_format/blob/f3e0ffe4dca7368da396dd543fecf11207c8fa9d/src/rebar3_format_prv.erl#L60-L66) in `rebar3_format`.

2022-01-26 07:49 UTC, elbrujohalcon submitted a review, later dismissed
I merged `main` here and fixed the tests, but now you should add tests with app dirs.
Also, I run it on my test app and…

```bash
===> typer: cannot access /src: No such file or directory
```

<details><summary>DEBUG=1 output</summary>

```bash
$ DEBUG=1 rebar3 typer --plt _build/default/rebar3_23.3.2_plt --show_exported
===> Load global config file /Users/fernandobenavides/.config/rebar3/rebar.config
===> 23.3.2 satisfies the requirement for minimum OTP version 23
===> Evaluating config script "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_build/default/plugins/hex_core/rebar.config.script"
===> 23.3.2 satisfies the requirement for minimum OTP version 19.3
===> Compile (apps)
===> 23.3.2 satisfies the requirement for minimum OTP version 21
===> Compile (apps)
===> Running hooks for compile in app rebar3_hank (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank) with configuration:
===> 	{pre_hooks, []}.
===> Running hooks for erlc_compile in app rebar3_hank (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank) with configuration:
===> 	{pre_hooks, []}.
===> Analyzing applications...
===> Compiling rebar3_hank
===> compile options: {erl_opts, [warn_unused_vars,warn_export_all,
                                         warn_shadow_vars,warn_unused_import,
                                         warn_unused_function,warn_bif_clash,
                                         warn_unused_record,
                                         warn_deprecated_function,
                                         warn_obsolete_guard,
                                         strict_validation,warn_export_vars,
                                         warn_exported_vars,debug_info]}.
===> files to analyze ["/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/rules/unnecessary_function_arguments.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/rules/unused_callbacks.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/rules/unused_record_fields.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/rules/unused_macros.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/rules/single_use_hrl_attrs.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/rules/unused_configuration_options.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/rules/unused_hrls.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/rules/single_use_hrls.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/rebar3_hank.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/hank_context.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/rebar3_hank_prv.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/hank_rule.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/hank.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank/src/hank_utils.erl"]
===> Running hooks for erlc_compile in app rebar3_hank (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank) with configuration:
===> 	{post_hooks, []}.
===> Running hooks for app_compile in app rebar3_hank (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank) with configuration:
===> 	{pre_hooks, []}.
===> Running hooks for app_compile in app rebar3_hank (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank) with configuration:
===> 	{post_hooks, []}.
===> Running hooks for compile in app rebar3_hank (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_hank) with configuration:
===> 	{post_hooks, []}.
===> 23.3.2 satisfies the requirement for minimum OTP version 23
===> Compile (apps)
===> Running hooks for compile in app rebar3_typer (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_typer) with configuration:
===> 	{pre_hooks, []}.
===> Running hooks for erlc_compile in app rebar3_typer (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_typer) with configuration:
===> 	{pre_hooks, []}.
===> Analyzing applications...
===> Compiling rebar3_typer
===> compile options: {erl_opts, [debug_info,warn_export_vars,
                                         warn_missing_specs,
                                         warn_unused_import,
                                         warnings_as_errors,
                                         {i,"src"}]}.
===> files to analyze ["/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_typer/src/rebar3_typer.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_typer/src/rebar3_mini_typer.erl",
                              "/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_typer/src/rebar3_typer_prv.erl"]
===> Running hooks for erlc_compile in app rebar3_typer (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_typer) with configuration:
===> 	{post_hooks, []}.
===> Running hooks for app_compile in app rebar3_typer (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_typer) with configuration:
===> 	{pre_hooks, []}.
===> Running hooks for app_compile in app rebar3_typer (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_typer) with configuration:
===> 	{post_hooks, []}.
===> Running hooks for compile in app rebar3_typer (/Users/fernandobenavides/Projects/elbrujohalcon/test_hank/_checkouts/rebar3_typer) with configuration:
===> 	{post_hooks, []}.
===> Expanded command sequence to be run: [app_discovery,typer]
===> Running provider: app_discovery
===> Found top-level apps: [test_hank]
	using config: [{src_dirs,["src"]},{lib_dirs,["apps/*","lib/*","."]}]
===> Running provider: typer
===> Looking for types to add...
===> Opts: #{edoc => false,
                    files_r => ["/src"],
                    io =>
                        #{abort => fun rebar_api:abort/2,
                          debug => fun rebar_api:debug/2,
                          info => fun rebar_api:info/2,
                          warn => fun rebar_api:warn/2},
                    mode => show_exported,no_spec => false,
                    plt => "_build/default/rebar3_23.3.2_plt",
                    show_succ => false}
Args: {args,[],["/src"],[]}
Analysis: {analysis,show_exported,[],[],
              {codeserver,0,#Ref<0.402083263.2257190914.158999>,
                  #Ref<0.402083263.2257190914.159003>,
                  #Ref<0.402083263.2257190914.159002>,
                  #Ref<0.402083263.2257190914.159000>,
                  #Ref<0.402083263.2257190914.159001>,
                  #Ref<0.402083263.2257190914.159005>,
                  #Ref<0.402083263.2257190914.159004>,
                  #Ref<0.402083263.2257190914.159006>,
                  #Ref<0.402083263.2257190914.159007>,
                  #Ref<0.402083263.2257190914.159008>,
                  #Ref<0.402083263.2257190914.159009>},
              {callgraph,
                  {digraph,#Ref<0.402083263.2257190914.159020>,
                      #Ref<0.402083263.2257190914.159021>,
    [...]

2022-01-27 08:35 UTC, elbrujohalcon requested changes

2022-01-27 08:35 UTC, elbrujohalcon commented on src/rebar3_typer_prv.erl
> +            filelib:wildcard("{src,lib,apps}"); % last ditch
```suggestion
            filelib:wildcard("{src,lib/*/src,apps/*/src}"); % last ditch
```

2022-01-27 08:35 UTC, elbrujohalcon commented on test/dummy/rebar.config
> +{erl_opts, [debug_info]}.
Let's move this file to `test/files/dummy/…`.

2022-01-27 08:35 UTC, elbrujohalcon commented on test/dummy/src/dummy.erl
> +-module(dummy).
This file as well.

2022-01-27 09:50 UTC, elbrujohalcon approved these changes

2022-01-27 09:51 UTC, pablocostass approved these changes

2022-01-27 10:01 UTC, merged